name: HTML Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Run HTMLHint on HTML Files
        run: htmlhint --config .htmlhintrc *.html
